type = "javascript"
account_id = ""                                               # Enter Cloudflare account ID
zone_id = ""                                                  # Enter Cloudflare zone ID

[build]
command = "npm install && npm run build"

[build.upload]
format = "service-worker"

[env.dev]
name = ""                                                     # Enter the dev worker's name
workers_dev = true

kv_namespaces = [{ binding = "", id = "", preview_id = "" }]  # Enter the Worker KV store for dev

[env.prod]
name = ""                                                     # Enter the prod worker's name
workers_dev = false
route = ""                                                    # Enter your production route

kv_namespaces = [{ binding = "", id = "", preview_id = "" }]  # Enter the Worker KV store for prod
