type = "javascript"
account_id = ""
zone_id = ""

[build]
command = "npm install && npm run build"

[build.upload]
format = "service-worker"

[env.dev]
name = "dev-mixurri"
workers_dev = true

kv_namespaces = [{ binding = "", id = "", preview_id = "" }]

[env.prod]
name = "mixurri"
workers_dev = false
route = ""

kv_namespaces = [{ binding = "", id = "", preview_id = "" }]
